# Generated by Django 4.2.7 on 2024-02-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='department_name',
            new_name='department',
        ),
    ]
