# Generated by Django 4.2.7 on 2024-02-27 18:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
